/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData soda = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData water = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData restroom = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData heart = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData heart_filled = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData back = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData sign_in_alt_solid = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData snacks = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData user_plus_solid = IconData(0xe808, fontFamily: _kFontFam);
}
